Calculator logic.
tzvaita/react-calculator pull request #4
Opened 2020-10-16 15:07 UTC by tzvaita

- Added two logic files.
- Implemented calculator function using switch statements.
- Used JS ES6 methods and imports.
- Checked code for errors.

2020-10-16 19:04 UTC, mosaaleb requested changes
#### Well done @tzvaita  :clap:

Most requirements are handled, yet we have some to work on before moving on. Check my comments below.

Please handle these requirements and submit a new code review.

##### Muhammad Ebeid

2020-10-16 19:04 UTC, mosaaleb commented on src/logic/calculate.js
> +const calculate = ({ total, next, operation }, btnName) => {
- [ ] it imports and uses it operate function from  `operate.js`.

calculate should use `operate` to calculate the `total` using the operate function.

![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone4/performOperate.png)

2020-10-16 19:04 UTC, mosaaleb commented on src/logic/operate.js
> +      return Big(numberOne) - Big(numberTwo);
- [ ] Since we are using big numbers, you need to use the calculation method (plug, minus, times, div and mod) provided by big.js
Take a look at the functions provided by it [here](https://mikemcl.github.io/big.js/#prototype-methods)

2020-10-19 14:12 UTC, mikenath223 requested changes
### Hello @tzvaita 👋


You've done pretty well on this, fixing a few issues raised in the previous review.

**STATUS: CHANGES REQUESTED.**

- [ ] Please check the comments made on the code.

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

2020-10-19 14:12 UTC, mikenath223 commented on src/logic/operate.js
> +  switch (operation) {
- [ ] Please also wrap numberTwo in Big number notation.

2020-10-19 14:13 UTC, mikenath223 commented on src/logic/operate.js
> +      return x.mod(numberTwo);
- [ ] This means percentage value, not modulus, kindly divide by `100` instead.

2020-10-19 14:19 UTC, mikenath223 requested changes
### Hi again @tzvaita 👋


**You are quite close to a full thumbs up. 💪**

Just fix this last change and you are good to go.

**STATUS: CHANGES REQUIRED.**

- [ ] Check  comment on the code.

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

2020-10-19 14:22 UTC, mikenath223 approved these changes
### CONGRATULATIONS  👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

HAPPY CODING👨‍💻

2020-10-21 08:50 UTC, merged